#!/usr/bin/env bash

command=$1
senha_path="$( cd "$(dirname "$0")"; cd .. ; pwd -P )"
support_path="$(cd "$(dirname "$0")" && pwd)"

generate_mocks() {
    mock_sources_path="$senha_path/Senha"
    mock_output_path="$senha_path/Senha-UnitTests/Support"
    if [ "$(ls $mock_output_path)" ]; then
        chmod 755 $mock_output_path/*
    fi

    $support_path/mockolo -s $mock_sources_path -d "$mock_output_path/Mocks.swift" -i "Senha" --enable-args-history

    if [ "$(ls $mock_output_path)" ]; then
        chmod 444 $mock_output_path/*
    fi
}

generate_strings() {
    strings_output_path="$senha_path/Senha/Base/Strings.swift"
    localizable_strings_path="$senha_path/Senha/Base/en.lproj/Localizable.strings"
    chmod 755 $strings_output_path
    swiftgen run strings $localizable_strings_path --templateName structured-swift5 --output $strings_output_path
    chmod 444 $strings_output_path
}

if [[ $command = "mocks" ]]; then
    echo "Generating mocks"
    generate_mocks

    echo "Finish 🍾"
fi

if [[ $command = "strings" ]]; then
    echo "Generating strings"
    generate_strings

    echo "Finish 🍾"
fi

