# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 11 Pro Max",
  "iPhone 8 Plus",
])

languages([
  "en-US",
  "pt-BR"
])

# The name of the scheme which contains the UI Tests
scheme("Senhas-UITests")
clear_previous_screenshots(true)
override_status_bar(true)

# For more information about all available options run
# fastlane action snapshot
